# Generated by Django 6.1 on 2026-09-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(default='Prescription', max_length=64)),
                ('facility', models.CharField(default='Metro General Hospital', max_length=128)),
                ('doctor', models.CharField(default='Dr. Michael Chen, MD', max_length=128)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('confidence', models.CharField(default='99.4%', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField(default=38)),
                ('gender', models.CharField(default='Female', max_length=32)),
                ('blood_group', models.CharField(default='A+', max_length=8)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('emergency_contact', models.CharField(default='+1 (555) 382-9912 (Spouse)', max_length=64)),
                ('primary_doctor', models.CharField(default='Dr. Michael Chen, MD (Cardiology)', max_length=128)),
                ('pin', models.CharField(default='1234', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('dose', models.CharField(default='500 mg', max_length=64)),
                ('frequency', models.CharField(default='3 times daily', max_length=64)),
                ('duration', models.CharField(default='7 days', max_length=64)),
                ('instruction', models.CharField(default='Take after meals', max_length=255)),
                ('timing', models.CharField(default='Morning, Noon, Night', max_length=64)),
                ('status', models.CharField(default='Active', max_length=32)),
                ('taken_today', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='api.medicaldocument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='api.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.patient'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='agent', max_length=16)),
                ('text', models.TextField()),
                ('urgency', models.CharField(default='normal', max_length=16)),
                ('quick_replies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.patient')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField(default=74)),
                ('bp_systolic', models.IntegerField(default=118)),
                ('bp_diastolic', models.IntegerField(default=78)),
                ('spo2', models.IntegerField(default=99)),
                ('temperature', models.FloatField(default=98.4)),
                ('glucose', models.IntegerField(default=92)),
                ('weight_kg', models.FloatField(default=64.0)),
                ('height_cm', models.FloatField(default=168.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_history', to='api.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
