# Generated by Django 6.1 on 2026-09-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=120)),
                ('otp_code', models.CharField(max_length=10)),
                ('identifier_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('ABHA', 'ABHA'), ('MOBILE', 'Mobile'), ('EMAIL', 'Email'), ('AUTO', 'Auto-detected')], default='AUTO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='mock_aadhaar_id',
            field=models.CharField(blank=True, db_index=True, help_text='Mock 12-digit Aadhaar Number (e.g. 5521 8934 1284 or 552189341284) standing in for UIDAI gateway', max_length=32, null=True, unique=True),
        ),
    ]
