# Generated by Django 6.1 on 2026-09-08 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification_patientprofile_mock_aadhaar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FAILED_LOGIN', 'Failed Login Attempt'), ('OTP_FLOOD', 'Excessive OTP Requests'), ('SPAM_DETECTED', 'Spam / Fraud Detected'), ('USER_BANNED', 'User Banned / Flagged'), ('USER_UNBANNED', 'User Restored'), ('IDENTIFIER_BLOCKED', 'Identifier Blacklisted'), ('IDENTIFIER_UNBLOCKED', 'Identifier Unblocked'), ('ROLE_CHANGED', 'User Role Modified'), ('ACCOUNT_DELETED', 'Account Removed'), ('SUSPICIOUS_GEO', 'Unusual Geographic Access')], max_length=50)),
                ('identifier', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=64)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_flagged_spammer',
            field=models.BooleanField(default=False, help_text='Flagged by security system or admin for spamming or suspicious activity'),
        ),
        migrations.AddField(
            model_name='user',
            name='spam_notes',
            field=models.CharField(blank=True, help_text='Security or admin notes on why user is flagged', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='spam_score',
            field=models.PositiveIntegerField(default=0, help_text='Risk score (0=clean, >50=warning, >80=high risk/auto-block)'),
        ),
        migrations.CreateModel(
            name='BlockedIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=150)),
                ('identifier_type', models.CharField(choices=[('IP', 'IP Address'), ('PHONE', 'Phone Number'), ('EMAIL', 'Email Address'), ('AADHAAR', 'Aadhaar Number'), ('ABHA', 'ABHA ID'), ('USERNAME', 'Username')], default='IP', max_length=20)),
                ('reason', models.TextField(help_text='Reason for blocking or blacklisting')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this block is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_identifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
