# Generated by Django 6.1 on 2026-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_chatmessage_is_emergency_chatmessage_quick_replies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalreading',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalreading',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
