# Generated by Django 6.1 on 2026-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vitalreading_height_cm_vitalreading_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='query_mode',
            field=models.CharField(blank=True, default='general', max_length=20),
        ),
    ]
