# Generated by Django 6.1 on 2026-09-05 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(max_length=64, unique=True)),
                ('patient_identifier', models.CharField(default='MK-78294', max_length=64)),
                ('purpose', models.CharField(choices=[('CARE_CONSULTATION', 'Direct Outpatient Consultation'), ('RECORD_SHARING', 'Health Record Sharing via ABDM'), ('AI_PROCESSING', 'AI Automated Clinical Structuring')], default='CARE_CONSULTATION', max_length=30)),
                ('status', models.CharField(choices=[('GRANTED', 'Consent Granted'), ('REVOKED', 'Consent Revoked'), ('EXPIRED', 'Consent Expired')], default='GRANTED', max_length=20)),
                ('hip_id', models.CharField(default='IN-HOSP-001', help_text='Health Information Provider ID', max_length=64)),
                ('hiu_id', models.CharField(default='IN-HIU-MEDIKIOSK', help_text='Health Information User ID', max_length=64)),
                ('fhir_resource_type', models.CharField(default='Bundle/Composition', max_length=50)),
                ('mock_fhir_bundle', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
