# Generated by Django 6.1 on 2026-09-05 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('patient_identifier', models.CharField(db_index=True, default='MK-78294', max_length=64)),
                ('purpose', models.CharField(choices=[('share_hospital', 'Share with Consulting Hospital & Doctor'), ('store_documents', 'Store & Digitize Medical Documents'), ('link_abha', 'Link to ABHA Digital Health Record (ABDM)'), ('ai_transcription', 'AI Automated Clinical Transcription')], default='share_hospital', max_length=50)),
                ('granted', models.BooleanField(db_index=True, default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('hip_id', models.CharField(default='IN-HOSP-001', max_length=64)),
                ('hiu_id', models.CharField(default='IN-HIU-MEDIKIOSK', max_length=64)),
                ('mock_fhir_bundle', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.DeleteModel(
            name='ConsentArtifact',
        ),
    ]
