# Generated by Django 6.1 on 2026-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0002_consentrecord_delete_consentartifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='patient_identifier',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
