# Generated by Django 6.1 on 2026-09-05 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('patient_identifier', models.CharField(default='MK-78294', max_length=64)),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='en', max_length=20)),
                ('mode', models.CharField(choices=[('TOUCH', 'Touch'), ('VOICE', 'Voice'), ('HYBRID', 'Hybrid')], default='HYBRID', max_length=20)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('AI', 'AI Kiosk Agent'), ('PATIENT', 'Patient'), ('SYSTEM', 'System Prompt')], max_length=20)),
                ('text', models.TextField()),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('entities_extracted', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='intake.intakesession')),
            ],
        ),
    ]
