# Generated by Django 6.1 on 2026-09-05 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='intakesession',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='intakesession',
            name='chief_complaint',
        ),
        migrations.RemoveField(
            model_name='intakesession',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='intakesession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='intakesession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakesession',
            name='current_stage',
            field=models.CharField(choices=[('CHIEF_COMPLAINT', 'Chief Complaint'), ('HPI', 'History of Present Illness (SOCRATES)'), ('PAST_HISTORY', 'Past Medical & Surgical History'), ('DRUG_ALLERGY', 'Medications & Allergies'), ('FAMILY_PERSONAL', 'Family & Personal History'), ('AYUSH', 'AYUSH / Ayurvedic Specifics'), ('COMPLETE', 'Intake Completed')], default='CHIEF_COMPLAINT', max_length=30),
        ),
        migrations.AddField(
            model_name='intakesession',
            name='department',
            field=models.CharField(default='General Medicine', max_length=100),
        ),
        migrations.AddField(
            model_name='intakesession',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_intake_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intakesession',
            name='flag_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='intakesession',
            name='flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='intakesession',
            name='is_ayush_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intakesession',
            name='progress_percent',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='intakesession',
            name='session_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='ClinicalHistoryDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('hpi', models.JSONField(blank=True, default=dict)),
                ('past_medical_history', models.JSONField(blank=True, default=list)),
                ('drug_history', models.JSONField(blank=True, default=list)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('family_history', models.JSONField(blank=True, default=list)),
                ('personal_history', models.JSONField(blank=True, default=dict)),
                ('ayush_fields', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_draft', to='intake.intakesession')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('patient', 'Patient'), ('ai', 'AI Kiosk Agent'), ('system', 'System')], max_length=20)),
                ('text', models.TextField()),
                ('input_mode', models.CharField(choices=[('voice', 'Voice (ASR)'), ('touch', 'Touch Selection'), ('text', 'Text Input')], default='touch', max_length=20)),
                ('suggested_answers', models.JSONField(blank=True, default=list)),
                ('extracted_entities', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='intake.intakesession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ConversationTurn',
        ),
    ]
