# Generated by Django 6.1 on 2026-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_rename_created_at_intakesession_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakesession',
            name='patient_identifier',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
