# Generated by Django 6.1 on 2026-09-05 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=64, unique=True)),
                ('patient_identifier', models.CharField(default='MK-78294', max_length=64)),
                ('title', models.CharField(default='Scanned Medical Document', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('file_url', models.CharField(blank=True, default='', max_length=500)),
                ('doc_type', models.CharField(choices=[('PRESCRIPTION', 'Prescription'), ('LAB_REPORT', 'Lab Report'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('IMAGING_REPORT', 'Imaging Report'), ('OTHER', 'Other')], default='PRESCRIPTION', max_length=30)),
                ('ocr_status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing OCR'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('extracted_entities', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='intake.intakesession')),
            ],
        ),
    ]
