# Generated by Django 6.1 on 2026-09-05 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('intake', '0002_rename_created_at_intakesession_started_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='medicaldocument',
            name='extracted_entities',
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='doc_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='doc_type',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Laboratory Report'), ('discharge_summary', 'Discharge Summary'), ('imaging', 'Diagnostic Imaging / Radiology'), ('other', 'Other Document')], default='prescription', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='ocr_status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing OCR'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='patient_identifier',
            field=models.CharField(db_index=True, default='MK-78294', max_length=64),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_documents', to='intake.intakesession'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='title',
            field=models.CharField(default='Medical Document', max_length=255),
        ),
        migrations.CreateModel(
            name='ExtractedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('medication', 'Medication / Prescription'), ('lab_result', 'Laboratory Test Result'), ('diagnosis', 'Clinical Diagnosis'), ('procedure', 'Surgical / Medical Procedure')], max_length=20)),
                ('structured_data', models.JSONField(default=dict)),
                ('document_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_abnormal', models.BooleanField(db_index=True, default=False)),
                ('abnormal_flag_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_records', to='documents.medicaldocument')),
            ],
            options={
                'ordering': ['-document_date', '-created_at'],
            },
        ),
    ]
