# Generated by Django 6.1 on 2026-09-05 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_id', models.CharField(max_length=64, unique=True)),
                ('patient_identifier', models.CharField(default='MK-78294', max_length=64)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Ready for Review'), ('DOCTOR_EDITED', 'Doctor Edited & Approved')], default='READY', max_length=20)),
                ('chief_complaints', models.JSONField(blank=True, default=list)),
                ('history_of_present_illness', models.TextField(blank=True, default='')),
                ('past_medical_history', models.JSONField(blank=True, default=list)),
                ('current_medications', models.JSONField(blank=True, default=list)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('vitals', models.JSONField(blank=True, default=dict)),
                ('doctor_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_summaries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='intake.intakesession')),
            ],
        ),
    ]
