# Generated by Django 6.1 on 2026-09-05 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_rename_created_at_intakesession_started_at_and_more'),
        ('summary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicianSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('patient_identifier', models.CharField(db_index=True, default='MK-78294', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (AI-Generated)'), ('IN_REVIEW', 'In Doctor Review'), ('CONFIRMED', 'Confirmed by Physician')], default='DRAFT', max_length=20)),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('hpi', models.TextField(blank=True, default='', help_text='History of Present Illness')),
                ('past_medical_surgical_history', models.TextField(blank=True, default='')),
                ('drug_history', models.JSONField(blank=True, default=list)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('family_history', models.TextField(blank=True, default='')),
                ('personal_history', models.TextField(blank=True, default='')),
                ('review_of_systems', models.TextField(blank=True, default='')),
                ('investigations', models.JSONField(blank=True, default=list, help_text='Lab test results with abnormal flags')),
                ('previous_procedures', models.JSONField(blank=True, default=list)),
                ('regional_language', models.CharField(default='hi', max_length=20)),
                ('bilingual_summary', models.JSONField(blank=True, default=dict)),
                ('doctor_notes', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_physician_summaries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physician_summaries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physician_summaries', to='intake.intakesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummaryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(default=dict)),
                ('revision_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='summary.physiciansummary')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ClinicalSummary',
        ),
    ]
