# Generated by Django 6.1 on 2026-09-05 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intake', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=64, unique=True)),
                ('patient_identifier', models.CharField(default='MK-78294', max_length=64)),
                ('severity', models.CharField(choices=[('LOW', 'Low Urgency'), ('MEDIUM', 'Moderate Urgency'), ('HIGH', 'High Urgency (Priority)'), ('CRITICAL', 'Critical Red-Flag (Immediate)')], default='HIGH', max_length=20)),
                ('category', models.CharField(choices=[('CARDIOVASCULAR', 'Cardiovascular Risk'), ('RESPIRATORY', 'Respiratory Distress'), ('NEUROLOGICAL', 'Neurological Signs'), ('DRUG_CONTRAINDICATION', 'Drug Interaction / Allergy Conflict'), ('SEPSIS_INFECTION', 'Sepsis / Severe Infection Risk'), ('OTHER', 'Other Clinical Alert')], default='DRUG_CONTRAINDICATION', max_length=30)),
                ('trigger_reason', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('vitals_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triage_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='intake.intakesession')),
            ],
        ),
    ]
