# Generated by Django 6.1 on 2026-09-05 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_rename_created_at_intakesession_started_at_and_more'),
        ('triage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagealert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='triagealert',
            name='category',
        ),
        migrations.RemoveField(
            model_name='triagealert',
            name='description',
        ),
        migrations.AddField(
            model_name='triagealert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_triage_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triagealert',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Clinical symptom trigger flagged for clinician review'),
        ),
        migrations.AddField(
            model_name='triagealert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagealert',
            name='status',
            field=models.CharField(choices=[('open', 'Open / Active'), ('acknowledged', 'Acknowledged by Staff'), ('resolved', 'Resolved by Clinician')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='triagealert',
            name='alert_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='triagealert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='triagealert',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_triage_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triagealert',
            name='patient_identifier',
            field=models.CharField(db_index=True, default='MK-78294', max_length=64),
        ),
        migrations.AlterField(
            model_name='triagealert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_triage_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triagealert',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_alerts', to='intake.intakesession'),
        ),
        migrations.AlterField(
            model_name='triagealert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low Urgency'), ('MEDIUM', 'Moderate Urgency'), ('HIGH', 'High Urgency (Priority)'), ('CRITICAL', 'Critical Red-Flag (Immediate Nurse Attention)')], db_index=True, default='HIGH', max_length=20),
        ),
        migrations.AlterField(
            model_name='triagealert',
            name='trigger_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
