# Generated by Django 6.1 on 2026-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_alter_triagealert_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagealert',
            name='patient_identifier',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
